steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/votesaathi-backend', './backend']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/votesaathi-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'votesaathi-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/votesaathi-backend'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '600'
images:
  - 'gcr.io/$PROJECT_ID/votesaathi-backend'
